language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: n5NENmMIK7EPYUWpfT6z2eubTZRslm+Nb/f8LYCHX98COupj40e9e2FDtsZLIFEbDqzxpEOIdkYIhlgu2I1WyC1viCDjQ4rOPgoKQAQf+RKU71KG/mzYDT3OxyE8OL+vEszf1SxSFCOt2ASuRdumzN+U8PT1CA0WGeVtp8seO6jENC/ZHvhfpj3KOxQXeoJ7o4KycH3XO5I9/dzQsFY1KxK4lJiDbbe101xjd/3TKGiGVb4hRHalFHzAXhuoXhyIqlb7qPhR7wiWCI+6y2K6hOfsn+kNfNoCegQtRdFsqeoHyd99eXwlxpiI3/vRi71oM2cMhALhwSwJu4VIsVZ2dTDHQ2dXHLO1mij1H28r0FlNFEZCE+JhMm7dsSxrZwmYUQjcROWj17c407FSF9x7P91cNMtfHW9UEqmoYb+Ppox1lcym30M3fFgmxgh2BG//CnOt9bG1KUYmDB/R7WlOg338dwCx0lcB0omlvyN7DFMhlkAqEBrZWX6tuvRJQQN8Jvkljs8qlq9z61DXccrAGhtRbFKUfVW+T/hdGyT8M3R5B3l0i++XvudiyBcM+Xzp01XDR5RcaKn8dnOPKkuOmWouUHRdhiDIyeNsnQkhnCNUgynrQwrogu9oQeFk1YOk0+ZiR51Ev+hyNor/GsEv2ETWKJhQp7JCQWCV0Xy/+qY=
  app: guarded-fortress-67027